### ISSUE TITLE
Text is not centered on bullet points

### ISSUE THREAD

**Issue by BrandonNolet** [Satchelmouth/Obsidian-Theme-WYConsole#5]
example: 

<img width="633" alt="image" src="https://github.com/user-attachments/assets/be7458af-0fe2-4052-9355-7ac3bc610fc2">

The text seems to be above the center point of the "bullet point"

**Comment by chrisdein** [comment]
Added `line-height: .9;` to `/* lists */` - trial and error, .9 seemed to work for me

``` css
/* lists */
.markdown-source-view.mod-cm6 .HyperMD-list-line .list-bullet:after {
	height: 10px;
	width: 10px;
	border-radius: 50%;
	background-color: transparent;
	content:'>';
	color: var(--col-ed-txt-ul-bullet);
	font-weight: bold;
	line-height: .9;
} 
```
